name: bimboo
favicon: null
layout_spectrum: 0.38431277335621417
typography_spectrum: 0.336365741211921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7621025738772005
  lightness: 0.75950124906376
  saturation: 0.831801867345348
  rhythmicContrast: 0.3305358327925205
purpose: []
